
scenario: quadrotor_multi
conf:
  quads_use_numba: True
  quads_num_agents: 2
  quads_mode: static_same_goal
  quads_episode_duration: 15.0
  quads_neighbor_encoder_type: no_encoder
  quads_neighbor_hidden_size: 0
  quads_neighbor_obs_type: none
  quads_neighbor_visible_num: 0
  replay_buffer_sample_prob: 0.75
  quads_obs_repr: xyz_vxyz_R_omega
  quads_collision_hitbox_radius: 2.0
  quads_collision_falloff_radius: 1.0
  quads_use_obstacles: False
  quads_obst_density: 0.2
  quads_obst_size: 1.0
  quads_obst_spawn_area: [6.0, 6.0]
  quads_use_downwash: False
  quads_room_dims: [10., 10., 10.]
  quads_view_mode: ['topdown', 'chase', 'global']
  quads_render: False
  quads_domain_random: False
  quads_obst_density_random: False
  quads_obst_size_random: False
  quads_obst_density_min: 0.05
  quads_obst_density_max: 0.2
  quads_obst_size_min: 0.3
  quads_obst_size_max: 0.6
  quads_collision_reward: 0.0
  quads_collision_smooth_max_penalty: 10.0
  quads_obst_collision_reward: 0.0
  anneal_collision_steps: 0.0
  with_pbt: False
  visualize_v_value: False