env: "voltage_control"

env_args:
    "voltage_barrier_type": "l1" # "l1", "l2", "bowl", "courant_beltrami", "bump"
    "voltage_weight": 1.0
    "q_weight": 0.1
    "line_weight": null
    "dq_dv_weight": null
    "history": 1
    "pv_scale": 1.0
    "demand_scale": 1.0
    "state_space": ["pv", "demand", "reactive", "vm_pu", "va_degree"]
    "v_upper": 1.05
    "v_lower": 0.95
    # "data_path": "amb/envs/voltage/data/case33_3min_final" # from the root of valtage_control environment folder
    "data_path": "data/case33_3min_final" # from the root of valtage_control environment folder
    "episode_limit": 240 # in time intervals
    "action_scale": 0.8
    "action_bias": 0
    "mode": distributed # distributed / decentralised
    "reset_action": True
    "seed": 0