experimentName: nni-explore-qmix
searchSpace:
  # common hyperparameters [don't change]
  algo_args.log_dir:
    _type: choice
    _value: ["#nni_dynamic"]
  # end common hyperparameters
  
  algo_args.num_env_steps:
    _type: choice
    _value: [3000000]
  main_args.algo:
    _type: choice
    _value: ["qmix"]
  main_args.env:
    _type: choice
    _value: ["smac"]
  main_args.run:
    _type: choice
    _value: [
        "single",
        # 'perturbation',
        # "traitor",
      ]
  env_args.map_name:
    _type: choice
    _value: ["3m", "3s_vs_5z", "4m_vs_3m", "4s_vs_5z"]
  algo_args.seed":
    _type: choice
    _value: [0, 1]

  # Exploration and Exploitation
  # Q-family
  algo_args.epsilon_anneal_time:
    _type: choice
    _value: [50000, 100000, 500000]

trialCommand: python -u ../../single_train.py --env smac --algo mappo --exp_name nni-explore-qmix --run single
trialCodeDirectory: .
# experimentWorkingDirectory: nni-experiments
trialGpuNumber: 1
trialConcurrency: 3
tuner:
  name: GridSearch
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 5
  gpuIndices: [0]
